ktor:
  deployment:
    port: "$PORT:8081"
  application:
    modules:
      - com.trobatapp.ApplicationKt.module

jwt:
  secret: "trobat-super-secret-key-change-in-production"
  issuer: "trobat-backend"
  audience: "trobat-app"
  realm: "Trobat API"